# Metody Numeryczne
## Laboratorium 1 (8 października 2021)

Na zajęciach będziemy pracowali w Pythonie z paczkami NumPy i SciPy

In [ ]:
# importujemy NumPy
# ponadto robimy to w taki sposób, by do funkcji i klas z tej 
# przestrzeni nazw dopierać się w wygodny sposób, dając im przedrostek "np."
import numpy as np

Paczka NumPy to wielki przyjaciel Numeryka-Pajtonisty. Dla przykładu, pozwala ona na niezwykle wygodne (w porównaniu z Pythonem-Bez-Numpy) reprezentowanie wektorów i macierzy

In [7]:
# definiujemy wektor
v = np.array([1,5,6,7])
print(f"Wektor v to\n {v}\n") # super wygodne f-stringi w Pythonie >= 3.6!

# definiujemy macierz
A = np.array([[4,1,6,5],
             [6,1,3,6],
             [5,6,8,9]])
print(f"Macierz A to\n {A}")

Wektor v to
 [1 5 6 7]

Macierz A to
 [[4 1 6 5]
 [6 1 3 6]
 [5 6 8 9]]


Rzecz jasna, wspierane są wszelkie podstawowe operacje na wektorach i macierzach, znane z naszego ukochanego GALu

In [23]:
print(f"A*v=\n{A@v}\n") # mnożenie wektora przez macierz
print(f"A'=\n{np.transpose(A)}\n") # transpozycja macierzy
B=A@np.transpose(A)
print(f"B:=A*A'=\n{A@np.transpose(A)}") # transpozycja macierzy

A*v=
[ 80  71 146]

A'=
[[4 6 5]
 [1 1 6]
 [6 3 8]
 [5 6 9]]

B:=A*A'=
[[ 78  73 119]
 [ 73  82 114]
 [119 114 206]]


Część z bardziej wyszukanych operacji algebroliniowych dostępna jest w podpaczce `np.linalg`

In [29]:
print(f"det(B)={np.linalg.det(B)}\n")
C=np.linalg.inv(B)
print(f"Macierz odwrotna do B to\n{C}\n")
print(f"Sprawdźmy! B*C=\n{B@C}")

det(B)=25548.000000000007

Macierz odwrotna do B to
[[ 0.15249726 -0.05761703 -0.05620792]
 [-0.05761703  0.07464381 -0.00802411]
 [-0.05620792 -0.00802411  0.04176452]]

Sprawdźmy! B*C=
[[ 1.00000000e+00  4.96130914e-16 -6.38378239e-16]
 [ 2.67841305e-15  1.00000000e+00 -4.99600361e-16]
 [ 1.31838984e-15 -6.93889390e-18  1.00000000e+00]]


In [30]:
%timeit np.linalg.det(B)

6.15 µs ± 71.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
